SELECT* from shopping_behavior_updated;
-- Q. what is he total revenue generated by male vs female
SELECT gender, SUM(purchase_amount) AS total_revenue  FROM shopping_behavior_updated
group by gender;

-- Q. which are the top 5 products with the highest average review rating?

select item_purchased, round(avg(review_rating),2) as average_product_rating
from shopping_behavior_updated
group by item_purchased order BY avg(review_rating) DESC
LIMIT 5;
             
-- Q.compare the average purchase amounts between standard and express shippping?
SELECT shipping_type , round(avg(purchase_amount),2) from shopping_behavior_updated
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q. do subscribed customer spend more ? compare average spend and total revenue between subscribers and non subscribers
SELECT subscription_sta, 
COUNT (customer_id), round(avg(purchase_amount),2) as avg_spend, sum(purchase_amount) as total_revenue from shopping_behavior_updated
--where subscription_sta in ('Yes','No')
GROUP By subscription_sta;
        --ORDER by total_revenue,avg_spend ASC
--Q.WHICH 5 PRODUCTS HAVE THE HIGHEST PERCENTAGE OF PURCHASE WITH DISCOUNT APPLIED?
SELECT item_purchased, 
ROUND(100*SUM(case WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS DISCOUNT_RATE from shopping_behavior_updated
---where discount_applied = 'Yes'-- OTHER WAY BUT WE CANT COUNT NO OF TOMES DISCOUNT APPLIED
GROUP BY item_purchased 
ORDER By DISCOUNT_RATE DESC
limit 5;

-- segment the customers into new returning and loyal based on their previous purchases, show the count of each segent.
with customer_type AS(
SELECT customer_id, previous_purchas,
case 
  when previous_purchas = 1 then 'new'
when previous_purchas BETWEEN 2 and 10 then 'returning'
else 'loyal'
END as customer_segment
from shopping_behavior_updated
)
SELECT customer_segment, count(*) as "number_of_customers" 
from customer_type
group by customer_segment;

-- what are the top 3 most purchased products within each category..
with item_counts AS (
SELECT item_purchased, category , COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS ITEM_RANK
from shopping_behavior_updated
GROUP BY category, item_purchased
)
SELECT ITEM_RANK , category, item_purchased, total_orders
from item_counts
where ITEM_RANK 

-- are customerswho are repeat buyers (more than 5 previous purchases ) also likely to subscribe

select subscription_sta, COUNT(customer_id) as repeat_buyers from shopping_behavior_updated
where previous_purchas > 5
group BY subscription_sta

--what is the revenue contribution of each group  

SELECT 
CASE 
    when age >= 10 and age <20 THEN 'young'
    when age >= 20 and age <40 THEN 'adult'
    when age >= 40 and age <60 THEN 'middle age'
  else 'senior'
  end as age_group,
  SUM(purchase_amount) as total_revenue FROM shopping_behavior_updated
group by age_group
order by total_revenue DESC


                


